language: node_js
node_js:
  - 14.0.0
cache: yarn

install: yarn install

script:
  - yarn run build

deploy:
  provider: gcs
  access_key_id: GOOGWEH4F4XE3U4KXBH556EW
  secret_access_key: GAHYaZ3he1SuqftRfwKrvPxR1BEBT3AF4X/CAcj1
  bucket: teste-alfredo
  local_dir: blog
  on:
    branch: master
  acl: public-read
