language: node_js
node_js:
  - 14.0.0
cache: yarn

install: yarn install

script:
  - yarn run build

deploy:
  provider: gcs
  access_key_id: ffac1fd2660d412b878a42349ae0f82f00db2f41
  secret_access_key:
    secure: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCanjAu3SlIRwWs\n/BfGHva6AumDYFenItSHJtNpnwW5A5J1ZMDMAIXUVBPli9/PzvrUuEocMYovXCKH\nrcOAdU/EcrB8T2ZfUV8WJ9ReqT2xmbaM/UilFeoea3VX5T5ZLUKAyz4X4slyMzCk\nn1a+fxZPjGp4JZv/wOqWwPiMnH8HxCGh6l77ihnLhJr9PIgBpoyLaLb2uUOjbQV/\nuWoPNlu1tTYszWRQEk5Nqhx7aqZGZMBzmhEFCyUj6uCXMFwbnYnLBUPad9cqnrZu\nGDtSc43qIA0m9cKvYfDR7YlRqqW0oUsNpyshOYkBz6wFcA7Pi7WgeiMC5WUfSvLi\nTUDSvcfVAgMBAAECggEAMgxBQXIiIjynCCrjkSRFrckyh+2AAeBC1eqJ5TbttckD\nt88gnwgOSb/bXuKLVCtFwuRSTNT2S0UyAiQLU8HlS4vqN5rF4tWmhzfmRKvYhevh\nDLsRsCorSaRz67sPFvORArqHA1lL5pTOSoMvI2Nkt+QWNITL/ZmW9axJ583iSoM/\nNzn3rsSzefPlU1f0xM6H1Wb3iZBWbw4LQSWXaAGUEZycnNfQh5F0saP8bv63c462\n8TPE+nyUm991pmOffnftRQE786c+ok3gBmOVXKYZQtUMvBmdtcpsElhWgwq3dFIa\nNhc1L/hO0Zg/0PHf3fbCWid796+jSLMAdaT/57I1wwKBgQDYMiOL3SRzBYENCldQ\nrI4kw1wYNqq6z/2jZPULT5Nd/YwjeFq0e7N83eh2F5zpdx6+724UHx617DAqKmZQ\nkZmXVBjvapNqjc+oCIghv+qCwoDA0UidKqELvuSqTRccDaImfo2LsTsS5F7pr5rw\nnt0Wt7wpYLAMpUjFKnOoFV7gkwKBgQC3FbmAwNS1VmNuAKMemKc52KICCymDFTwm\n1+hIgByuhzxGt7N+DSZFdgwxGOQcovuQ1yKjorq7a5iK2Znm7KJjZU3cudp3AiLI\n2+Rrp5mhv+C1996Epmo82iqSerklolHXzKvBGr29BTzZwar91p/uMIRpCpftf2Sx\nKi5B8iK+9wKBgQC1tN5fbUx3SAcBGNHuQjlt+KxsxXWVcb6yF+ZEzWsEsleYcE18\nKAPhTPlWV95P8whqXf5c9xLuwEZzChPYX6eBovMaNq8T/YCssA8KnqzRnfxtEvk+\n71dP8e9qm0RzFZpVVERPRnRqGnsTWb6Vwk/8Cg0hkdwlpL2WyWlPujZ19QKBgQCL\nIJ0o9GAvtQg17ZIHjCV31eG2/9h53kcplWTUw1YIYogxjSN/JGry2fQF0051XH0i\n4flWtDCGgAsZaKaFT0lPkwoKM8mKKjtYu5DnJiOfQPp4DXYxA20z9O3pBg1wRds/\nzC6wvat12mcVaxCPeOtry76zO/Ob7PUNlGo2ftRcnQKBgBusv3+peByytLK9izjI\n4I3+L92BKxvLlyLTcLxndbBMzG6ZLV5d6sqw31HSjbOFAFzKyRoc8tXPoByoGdRp\nso4luWupvdu19mMEFZDR1bpbKUdm0boM3QPf3bdz2gMADLcyckvpQMg3Up8q3qIk\nyTAqQwj9i6hUQFpZ1pmZ6qoc
  bucket: teste-alfredo
  local_dir: build
  on:
    branch: master
