language: node_js
node_js:
  - 14.0.0
cache: yarn

install: yarn install

script:
  - yarn run build

deploy:
  provider: gcs
  access_key_id: root-beanbag-269220
  secret_access_key:
    secure: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCanjAu3SlIRwWs/BfGHva6AumDYFenItSHJtNpnwW5A5J1ZMDMAIXUVBPli9/PzvrUuEocMYovXCKHrcOAdU/EcrB8T2ZfUV8WJ9ReqT2xmbaM/UilFeoea3VX5T5ZLUKAyz4X4slyMzCkn1a+fxZPjGp4JZv/wOqWwPiMnH8HxCGh6l77ihnLhJr9PIgBpoyLaLb2uUOjbQV/uWoPNlu1tTYszWRQEk5Nqhx7aqZGZMBzmhEFCyUj6uCXMFwbnYnLBUPad9cqnrZuGDtSc43qIA0m9cKvYfDR7YlRqqW0oUsNpyshOYkBz6wFcA7Pi7WgeiMC5WUfSvLiTUDSvcfVAgMBAAECggEAMgxBQXIiIjynCCrjkSRFrckyh+2AAeBC1eqJ5TbttckDt88gnwgOSb/bXuKLVCtFwuRSTNT2S0UyAiQLU8HlS4vqN5rF4tWmhzfmRKvYhevhDLsRsCorSaRz67sPFvORArqHA1lL5pTOSoMvI2Nkt+QWNITL/ZmW9axJ583iSoM/Nzn3rsSzefPlU1f0xM6H1Wb3iZBWbw4LQSWXaAGUEZycnNfQh5F0saP8bv63c4628TPE+nyUm991pmOffnftRQE786c+ok3gBmOVXKYZQtUMvBmdtcpsElhWgwq3dFIaNhc1L/hO0Zg/0PHf3fbCWid796+jSLMAdaT/57I1wwKBgQDYMiOL3SRzBYENCldQrI4kw1wYNqq6z/2jZPULT5Nd/YwjeFq0e7N83eh2F5zpdx6+724UHx617DAqKmZQkZmXVBjvapNqjc+oCIghv+qCwoDA0UidKqELvuSqTRccDaImfo2LsTsS5F7pr5rwnt0Wt7wpYLAMpUjFKnOoFV7gkwKBgQC3FbmAwNS1VmNuAKMemKc52KICCymDFTwm1+hIgByuhzxGt7N+DSZFdgwxGOQcovuQ1yKjorq7a5iK2Znm7KJjZU3cudp3AiLI2+Rrp5mhv+C1996Epmo82iqSerklolHXzKvBGr29BTzZwar91p/uMIRpCpftf2SxKi5B8iK+9wKBgQC1tN5fbUx3SAcBGNHuQjlt+KxsxXWVcb6yF+ZEzWsEsleYcE18KAPhTPlWV95P8whqXf5c9xLuwEZzChPYX6eBovMaNq8T/YCssA8KnqzRnfxtEvk+71dP8e9qm0RzFZpVVERPRnRqGnsTWb6Vwk/8Cg0hkdwlpL2WyWlPujZ19QKBgQCLIJ0o9GAvtQg17ZIHjCV31eG2/9h53kcplWTUw1YIYogxjSN/JGry2fQF0051XH0i4flWtDCGgAsZaKaFT0lPkwoKM8mKKjtYu5DnJiOfQPp4DXYxA20z9O3pBg1wRds/zC6wvat12mcVaxCPeOtry76zO/Ob7PUNlGo2ftRcnQKBgBusv3+peByytLK9izjI4I3+L92BKxvLlyLTcLxndbBMzG6ZLV5d6sqw31HSjbOFAFzKyRoc8tXPoByoGdRpso4luWupvdu19mMEFZDR1bpbKUdm0boM3QPf3bdz2gMADLcyckvpQMg3Up8q3qIkyTAqQwj9i6hUQFpZ1pmZ6qoc
  bucket: teste-alfredo
  local_dir: build
  on:
    branch: master
